version: '3'

services:
  # Should be moved to a separate repo
  ingress:
    image: traefik:1.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

  app:
    image: lucasvanlierop/website
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lucasvanlierop-web"
      - "traefik.frontend.rule=Host:lucasvanlierop.nl,www.lucasvanlierop.nl"
      - "traefik.port=80"
      - "traefik.docker.network=lucasvanlierop-website_default"
