debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "lucasvanlierop.nl"
watch = true
exposedbydefault = false

[acme]
email = "me@lucasvanlierop.nl"
storage = "acme.json"
OnHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
