env:
  global:
    - HOST_UID=$UID
    - HOST_GID=$GID

services:
  - docker

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make

after_failure:
  - docker-compose logs

branches:
  only:
    - master
