env:
  global:
    - HOST_UID=$UID
    - HOST_GID=$GID
    - TRAVIS=on

services:
  - docker

before_script:
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

script:
  - make test

after_failure:
  - docker-compose logs

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD && docker push lucasvanlierop/website:latest; fi

branches:
  only:
    - master

cache:
  directories:
    - ~/.composer/cache
