env:
  global:
    - HOST_UID=$UID
    - HOST_GID=$GID

services:
  - docker

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test

after_failure:
  - docker-compose logs

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD && docker push lucasvanlierop/website:latest; fi

branches:
  only:
    - master
