version: '2'

services:
  app:
    container_name: lucasvanlierop-website-app
    image: lucasvanlierop/website-app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:80
