version: '2'

services:
  app:
    restart: always
    container_name: lucasvanlierop-website
    image: lucasvanlierop/website
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:80
