version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  app:
    extends:
      file: env/default/docker-compose.yml
      service: app
    volumes:
      - ./output_dev:/usr/share/nginx/html
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lucasvanlierop-web"
      - "traefik.frontend.rule=Host:lucasvanlierop.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  sass:
    extends:
      file: env/default/docker-compose.yml
      service: sass

  sculpin:
    extends:
      file: env/default/docker-compose.yml
      service: sculpin
    environment:
      XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
      PHP_IDE_CONFIG: "serverName=lucasvanlierop.nl.localhost"
    command: sh -c 'composer install && vendor/bin/sculpin generate --watch'
