title: Lucas van Lierop Blog
subtitle: About software development, cars, music and more
url: https://lucasvanlierop.nl
author: Lucas van Lierop
email: me@lucasvanlierop.nl

disqus:
    shortname: lucas-van-lierop
