version: '2'

services:
  app:
    extends:
      file: ../default/docker-compose.yml
      service: app
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
  sass:
    extends:
      file: ../default/docker-compose.yml
      service: sass

  sculpin:
    extends:
      file: ../default/docker-compose.yml
      service: sculpin
