version: '2'

services:
  app:
    restart: on-failure
    container_name: lucasvanlierop-website
    image: lucasvanlierop/website

  sass:
    restart: on-failure
    container_name: lucasvanlierop-website-sass
    image: lucasvanlierop/website-sass
    build:
      context: ../../
      dockerfile: docker/sass/Dockerfile
    command: --watch /app/src/scss:/app/src/content/css
    user: $HOST_UID:$HOST_GID
    volumes:
      - ../../:/app

  spress:
    container_name: lucasvanlierop-website-spress
    image: pantelm/spress
    command: site:build --watch
    restart: on-failure
    user: $HOST_UID:$HOST_GID
    volumes:
      - ../../:/app
