version: '2'

services:
  app:
    restart: on-failure
    container_name: lucasvanlierop-website
    image: lucasvanlierop/website

  sass:
    restart: on-failure
    container_name: lucasvanlierop-website-sass
    image: lucasvanlierop/website-sass
    build:
      context: ../../
      dockerfile: docker/sass/Dockerfile
    command: --watch /app/source/scss:/app/source/css
    user: $HOST_UID:$HOST_GID
    volumes:
      - ../../:/app

  sculpin:
    build:
      context: ../../docker/sculpin
    restart: on-failure
    container_name: lucasvanlierop-website-sculpin
    user: $HOST_UID:$HOST_GID
    working_dir: /app
    environment:
      HOME: /home
    volumes:
      - ../../:/app
      - ~/.composer:/home/.composer
    command: vendor/bin/sculpin generate --watch
